# Generated by Django 2.0.7 on 2018-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DotPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('year', models.PositiveIntegerField()),
                ('rate', models.FloatField()),
            ],
            options={
                'ordering': ['meeting_date', 'year', 'rate'],
            },
        ),
    ]
